(define (problem sokoban-2.1)
	(:domain sokoban-domain)
	(:objects north south east west A1 A2 A3 A5 B1 B2 B3 B4 B5 C2 C3 D2 D3 bot block1)
	(:init (robot bot) (block block1) (locatedAt bot B4) (locatedAt block1 C2)
			(free A1) (free A2) (free A3) (free A5) (free B1) (free B2) (free B3) (free B5)
		    (free C3) (free D2) (free D3)	
			(adjacent A1 A2 north) (adjacent A2 A3 north) (adjacent A2 A1 south) (adjacent A3 A2 south)  
			(adjacent B1 B2 north) (adjacent B2 B3 north) (adjacent B2 B1 south) (adjacent B3 B2 south)  
			(adjacent B3 B4 north) (adjacent B4 B5 north) (adjacent B4 B3 south) (adjacent B5 B4 south)    
			(adjacent C2 C3 north) (adjacent D2 D3 north) (adjacent C3 C2 south) (adjacent D3 D2 south)
			(adjacent A1 B1 east) (adjacent A2 B2 east) (adjacent A3 B3 east)
			(adjacent B1 A1 west) (adjacent B2 A2 west) (adjacent B3 A3 west)
			(adjacent A5 B5 east) (adjacent B2 C2 east) (adjacent B3 C3 east) 
			(adjacent B5 A5 west) (adjacent C2 B2 west) (adjacent C3 B3 west) 
			(adjacent C2 D2 east) (adjacent C3 D3 east) 
			(adjacent D2 C2 west) (adjacent D3 C3 east)
	)
	(:goal (locatedAt block1 B5))
)
