(define (domain sokoban-domain)
	(:predicates (robot ?x) (block ?x) (locatedAt ?x ?loc) (free ?loc) (adjacent ?loc1 ?loc2 ?dir))
	(:action move
		:parameters (?dir ?robot ?loc1 ?loc2)
		:precondition (and (robot ?robot)
							(locatedAt ?robot ?loc1)
							(adjacent ?loc1 ?loc2 ?dir)
							(free ?loc2))
		:effect (and (not (locatedAt ?robot ?loc1))
						(locatedAt ?robot ?loc2)
						(not (free ?loc2))
						(free ?loc1))
	)
	(:action push
		:parameters (?dir ?robot ?block ?loc1 ?loc2 ?loc3)
		:precondition (and (robot ?robot)
							(block ?block)
							(locatedAt ?robot ?loc1)
							(locatedAt ?block ?loc2)
							(free ?loc3)
							(adjacent ?loc1 ?loc2 ?dir)
							(adjacent ?loc2 ?loc3 ?dir))
		:effect (and (not (locatedAt ?robot ?loc1))
						(locatedAt ?robot ?loc2)
						(not (locatedAt ?block ?loc2))
						(locatedAt ?block ?loc3)
						(not (free ?loc3))
						(free ?loc1))))